language: ruby
rvm:
  - 2.4.1
before_script:
  - gem install awesome_bot
script:
  - >
    awesome_bot -f README.md --allow-ssl --allow-redirect --allow-dupe
    --white-list www.linkedin.com,www.hostelworldgroup.com,www.olxgroup.com,www.prozis.com,www.glintt.com,oracle.com
